Add LFS backup, configure nginx client_max_body_size

diff --git a/templates/default/backup.sh.erb b/templates/default/backup.sh.erb
--- a/templates/default/backup.sh.erb
+++ b/templates/default/backup.sh.erb
@@ -10,19 +10,35 @@ if [ ! -d "$OUT_DIR" ]; then
   exit 2
 fi
 
-ARCHIVE_NAME=`date +"%Y_%m_%d__%H_%M_%S.zip"`
+RUN_USER=`id -un`
+RUN_GROUP=`id -gn`
+
+GOGS_ARCHIVE_NAME=`date +"gogs__%Y_%m_%d__%H_%M_%S.zip"`
 
 cd "<%= @user_home %>"
-sudo su <%= @user %> -c " <%= @gogs_work_dir %>/gogs backup --verbose --archive-name $ARCHIVE_NAME"
-ARCHIVE_PATH="<%= @user_home %>/$ARCHIVE_NAME"
+sudo su <%= @user %> -c " <%= @gogs_work_dir %>/gogs backup --verbose --archive-name $GOGS_ARCHIVE_NAME"
+GOGS_ARCHIVE_PATH="<%= @user_home %>/$GOGS_ARCHIVE_NAME"
 
-if [ ! -f "$ARCHIVE_PATH" ]; then
+if [ ! -f "$GOGS_ARCHIVE_PATH" ]; then
   echo "An error occured"
   exit 3
 fi
 
-ARCHIVE_NEW_PATH="$OUT_DIR/$ARCHIVE_NAME"
-sudo mv "$ARCHIVE_PATH" "$ARCHIVE_NEW_PATH"
-RUN_USER=`id -un`
-RUN_GROUP=`id -gn`
-sudo chown "$RUN_USER:$RUN_GROUP" "$ARCHIVE_NEW_PATH"
+GOGS_ARCHIVE_NEW_PATH="$OUT_DIR/$GOGS_ARCHIVE_NAME"
+sudo mv "$GOGS_ARCHIVE_PATH" "$GOGS_ARCHIVE_NEW_PATH"
+sudo chown "$RUN_USER:$RUN_GROUP" "$GOGS_ARCHIVE_NEW_PATH"
+
+LFS_ARCHIVE_NAME=`date +"lfs__%Y_%m_%d__%H_%M_%S.tar"`
+
+cd "<%=  @lfs_dir_base %>"
+sudo tar -cvf $LFS_ARCHIVE_NAME <%= @lfs_dir_name %>
+LFS_ARCHIVE_PATH="<%= @lfs_dir_base %>/$LFS_ARCHIVE_NAME"
+
+if [ ! -f "$LFS_ARCHIVE_PATH" ]; then
+  echo "An error occured"
+  exit 4
+fi
+
+LFS_ARCHIVE_NEW_PATH="$OUT_DIR/$LFS_ARCHIVE_NAME"
+sudo mv "$LFS_ARCHIVE_PATH" "$LFS_ARCHIVE_NEW_PATH"
+sudo chown "$RUN_USER:$RUN_GROUP" "$LFS_ARCHIVE_NEW_PATH"
